---
###-------------------------------------------------main.yml vars
mysql_only: 0
mysql_expire_logs_days: 7
galera_install: 0
galera_users: 0
galera_config: 0
galera_new_cluster: 0
galera_restart_cluster: 0
galera_uninstall: 0
galera_restart: 0
mem_persent: 50
galera_server_id: >
  {%- if not mysql_only -%}
  {{ hostvars[ ansible_play_hosts.0 ].ansible_default_ipv4.address.split('.')[-1] }}
  {%- else -%}
  {{ ansible_default_ipv4.address.split('.')[-1] }}
  {%- endif -%}
change_system_var_dyn: 0
backup: 0
check: 0
###-------------------------------------------------repos.yml vars
mariadb_release: 10.2
galera_mariadb_repo: ""
galera_percona_repo: "ORGLOT_OFFICE_Percona_Percona_5_release_for_RHEL7_x86_64"
###-------------------------------------------------packages.yml vars
#galera_percona_repo defined earlier
#galera_mariadb_repo defined earlier
galera_mysql_version: "latest"
galera_nodes_pkgs:
  - MariaDB-client-{{ galera_mysql_version }}
  - MariaDB-server-{{ galera_mysql_version }}
  - MariaDB-shared-{{ galera_mysql_version }}
  - MariaDB-common-{{ galera_mysql_version }}
  - MySQL-python
  - policycoreutils-python
  - gzip
percona_xtrabackup_version: ""
galera_percona_pkgs:
  - percona-xtrabackup-24{{ percona_xtrabackup_version }}
  - perl-Digest-MD5
  - qpress

galera_all_pkgs:
  - socat
  - galera
  # - xinetd https://confluence.stoloto.ru/pages/viewpage.action?pageId=74318059

###-------------------------------------------------selinux.yml vars
mysql_directories:
  - /var/lib/mysql
  - /var/log/mysql
###-------------------------------------------------users.yml vars
mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63623964653765346338313862643831626130623739396265653761633165333531353739633366
          3735343265346363363031626166616438363661313434340a633763613335613361326331376638
          62613236303331616232623432323234353230613732633961396366336264363630616136373136
          6562326330353030340a386637643565643732346163336565323561613765383664323933393237
          66303166613833323862376331616433393765303865336633623633643138646333

galera_sst_user: replicator
galera_sst_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65653464396138333231636633396334313663396661616165303132343261363534343536303966
          6265646261663830636564303361376536323363613031320a623134323965323564623836326631
          34376339373730643133313933343837633462613639643937363238663939626262373863313261
          3839643464343433630a633462323266643339316638373063373535633230396438353339653166
          34303434343635636437303164343332393962656239353235316166393463613531
clustercheck_mysql_user: clustercheck
clustercheck_mysql_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      33393161313439396439393163323636643430393032383630393961333932646331653237626364
      6265396337343066373738333037333734333438366433340a623037366239613032373135633430
      31633338656466666137633833666666636330323732646238303335396266333739313566313330
      3735646466313630370a393838613636356361623539323733366135313038396430363130636635
      3763
mysql_users:
  - name: "{{ clustercheck_mysql_user }}"
    host: "localhost"
    grants: "*.*:PROCESS"
    password: "{{ clustercheck_mysql_pass }}"

  - name: "{{ logrotate_mysql_user }}"
    host: "localhost"
    password: "{{ logrotate_mysql_pass }}"
    grants: "*.*:RELOAD"
###-------------------------------------------------config_cnf.yml vars
#mysql_directories defined earlier
galera_wsrep_cluster_name: cluster
galera_wsrep_cluster_port: 4567
galera_configs:
- |
    [mysqld]
    bind-address=0.0.0.0
    character_set_server=utf8
    collation_server=utf8_general_ci
    datadir={{ mysql_directories.0 }}
    expire_logs_days={{ mysql_expire_logs_days }}
    general_log_file={{ mysql_directories.1 }}/mariadb.log
    gtid_domain_id=1
    gtid_ignore_duplicates=1
    gtid_strict_mode=1
    init_connect='SET NAMES utf8'
    key_buffer_size=20M
    lc_messages=en_US
    log_bin_index={{ mysql_directories.1 }}/mariadb-bin.index
    log_bin_trust_function_creators=1
    log_bin={{ mysql_directories.1 }}/mariadb-bin
    log_slave_updates=1
    log_slow_rate_limit=1
    log_slow_verbosity=query_plan
    log_warnings=2
    long_query_time=0.5
    max_allowed_packet=10M
    max_binlog_size=100M
    max_connections={{ galera_max_connections }}
    open_files_limit=65536
    server-id={{ galera_server_id }}
    skip-name-resolve
    slow_query_log_file={{ mysql_directories.1 }}/mariadb-slow.log
    slow_query_log=1
    sync_binlog=1
    table-open-cache=10000


    transaction-isolation=REPEATABLE-READ #Default value.
    #tag6.8   or redmine#4863
    table_open_cache=16384
    table_definition_cache=16384

    #From OETS
    slave-net-timeout=21600

    relay-log={{ mysql_directories.1 }}/mysql-relay-bin.log
    bulk_insert_buffer_size=256M  # early was 8388608
    innodb_log_buffer_size=8M     # early was 1048576
    innodb_log_file_size=128M     # early was 5242880
    innodb_thread_concurrency=0  # early was 8
    thread_cache_size=32          # early was 16
    thread_stack=256K             # early was 196608

    [mariadb]
    binlog_format=row
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size={{ innodb_buffer_pool_size }} # up to {{mem_persent}}% RAM
    innodb_file_per_table=1
    innodb_flush_log_at_trx_commit=1
    innodb_flush_method=O_DIRECT
    max_prepared_stmt_count=65536
    innodb_print_all_deadlocks=1
- |
    [galera]
    wsrep_cluster_address="gcomm://
    {%- for host in groups['galera-db']|default([]) -%}
      {{ hostvars[host].cluster_ip }}:{{ galera_wsrep_cluster_port }}
      {%- if not loop.last -%},{%- endif -%}
    {%- endfor -%}"
    wsrep_cluster_name={{ galera_wsrep_cluster_name }}
    wsrep_gtid_domain_id=5
    wsrep_gtid_mode=1
    wsrep_node_address={{ cluster_ip }}:{{ galera_wsrep_cluster_port }}
    wsrep_node_name="{{ inventory_hostname_short }}"
    wsrep_on=ON
    wsrep_provider_options="gmcast.listen_addr=tcp://0.0.0.0:{{ galera_wsrep_cluster_port }};gcache.size=1G;gcache.recover=yes"
    wsrep_provider=/usr/lib64/galera/libgalera_smm.so
    wsrep_slave_threads=1
    wsrep_sst_auth="{{ galera_sst_user }}:{{ galera_sst_pass }}"
    wsrep_sst_method=xtrabackup-v2
    wsrep_sst_donor="
    {%- for host in (ansible_play_hosts | difference(groups['arbitrator'])) -%}
      {%- if hostvars[host].inventory_hostname_short != inventory_hostname_short -%}
      {{ hostvars[host].inventory_hostname_short }},
      {%- endif -%}
    {%- endfor -%}"

###-------------------------------------------------config.yml vars
galera_wsrep_cluster_net: 10.200.83.0/24
#galera_wsrep_cluster_name defined earlier
#galera_wsrep_cluster_port defined earlier
#mysql_directories defined earlier

###-------------------------------------------------logrotate.yml vars
logrotate_file: /etc/logrotate.d/mysql-server
logrotate_ssh_path: /var/lib/logrotate/.ssh
logrotate_ssh_key_path: "{{ logrotate_ssh_path }}/loguser_id_rsa"
logrotate_mycnf_dir: /var/lib/logrotate
logrotate_mycnf: "{{ logrotate_mycnf_dir }}/.my.cnf"
logrotate_mysql_user: logrotate
logrotate_mysql_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63366632323931356434323633343230303630346263613334653463326232623565656638643134
          3532346265663061636564656361386263303864396232320a396239636263306439376163303264
          39623665623934303761386266393834636364653263393935343235353365323062613163626337
          3165316337376638390a393665666561393235663861633362383363663132323237323535363766
          65303330356166326238333261303438383165656266303932313363313331363132
logrotate_server: backup.tsed.orglot.office
logrotate_remote_user: backupstore
logrotate_hostname_short: "{{ inventory_hostname_short }}"

#specify logrotate_project_name as a project_name, ex:gate
logrotate_project_name: uspecified
logrotate_slow_query_log_file: 0
logrotate_mysql_slow_log_file: ''
logrotate_send_to_bkp: 1

###-------------------------------------------------ops/ununstall.yml vars
galera_uninstall_pkgs:
  - MariaDB-client-{{ galera_mysql_version }}
  - MariaDB-server-{{ galera_mysql_version }}
  - MariaDB-shared-{{ galera_mysql_version }}
  - MariaDB-common-{{ galera_mysql_version }}
  - percona-xtrabackup-24{{ percona_xtrabackup_version }}
  - socat
  - galera
