---
- name: 1111 add mariadb repo
  blockinfile:
    path: /etc/yum.repos.d/mariadb.repo
    create: yes
    block: |
      [mariadb]
      name = MariaDB
      baseurl = http://yum.mariadb.org/{{ mariadb_release }}/rhel7-amd64
      gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck=1
  when: galera_mariadb_repo == ''

- name: 1111 add percona repo
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present
  when: galera_percona_repo == ''
