---
- block:
  - name: 1011 restorecon mysql dirs
    shell: restorecon -Rv "{{ item }}"
    with_items: "{{ mysql_directories }}"

  - name: 1011 add mysqld to permissive mode
    selinux_permissive:
      domain: mysqld_t
      permissive: True

  - name: 1011 semanage myscl dir context
    shell: semanage fcontext --add -s unconfined_u -t mysqld_db_t '/var/lib/mysql/*'

  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled' and inventory_hostname not in groups.arbitrator|default([])
